### ISSUE TITLE
stencil.core.d.ts is missing in build

### ISSUE THREAD

**Issue by StefanNieuwenhuis** [ionic-team/stencil-component-starter#81]
See: https://github.com/ionic-team/stencil/issues/1705

**stencil-component-starter version: `0.0.1`**
**@stencil/core version: `^1.0.7`**

### I'm submitting a:
[x] Bug report

### Current behavior:
After the first build (`npm run build`) `./dist/types/stencil.core.d.ts` isn't generated, hence missing.

### Expected behavior:
After executing `npm run build` `./dist/types/stencil.core.d.ts` is generated and available.

### Related code:
The problem is in `package.json`:
```
{
    ...
    "types": "dist/types/index.d.ts",
    ...
}
```

`types` refers to `index.d.ts` and this one doesn't exist before building and therefore `stencil.core.d.ts` is missing.

**Comment by gtranter** [comment]
My experience is that stencil.core.d.ts gets built sometimes. It is not a "fresh build" problem. Our build script removes dist entirely, so each build for us is "fresh". A pattern that has emerged is related to the order of the completion of two of Stencil's tasks:
```
[50:40.3]  bundling components finished in 16.12 s
[50:41.9]  type checking finished in 17.91 s
```
When bundling components completes before type checking, stencil.core.d.ts does not get added. This seems to happen most of the time. Otherwise it is added.

Still using index.d.ts as the type file.

**Comment by rwaskiewicz** [comment]
Closing, as `stencil.core.d.ts` is no longer being generated by Stencil 2.X
