### ISSUE TITLE
package-lock.json is invalid

### ISSUE THREAD

**Issue by zaki-yama** [ionic-team/stencil-component-starter#82]
When I create a starter project with `npm init stencil` or directly clone this repository and run `npm ci`, a following error occurs.

```
$ npm init stencil
✔ Pick a starter › component
✔ Project name › stenciljs-playground

✔ All setup  in 19 ms

$ cd stenciljs-playground
$ npm ci
npm ERR! cipm can only install packages when your package.json and package-lock.json or npm-shrinkwrap.json are in sync. Please update your lock file with `npm install` before continuing.
npm ERR!
npm ERR!
npm ERR! Invalid: lock file's @stencil/core@1.3.0 does not satisfy @stencil/core@^1.3.3
npm ERR!
```

**Comment by rwaskiewicz** [comment]
👋 I apologize it taking so long for the team to get back to you on this - we’re still relatively new and are working on the best strategy for triaging issues. 

The reason you are seeing this issue is that `npm ci` requires a package-lock to run, which is not provided in this repo. This is by design, as consumers may use different package managers (yarn, npm v6 and under, npm v7) all which produce a different type of lock file. 

Hopefully that addresses the issue!
